"""new fields in user model

Revision ID: 86404a286032
Revises: 9f645f015fb8
Create Date: 2022-08-22 21:31:27.228924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86404a286032'
down_revision = '9f645f015fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=404), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
